### PR TITLE
login page fixed and responsive

### PR DESCRIPTION
**Pull request by INam1995**
I have fixed the styling of login page and  made login page responsive .

I have made the page responsive, changed background image, fixed minor styling issues, linked files properly, changed fonts styles and improved the overall appearance of the page

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by dhanrajchaurasia** [comment]
why there are so many mismatches (line changes)? you have removed 2000 lines and added the same 2000 lines? [kindly fix it so that I can see the actual changes]

**Comment by INam1995** [comment]
Sorry sir , i did mistake ,  creating new PR .

**Comment by INam1995** [comment]
sir I did a mistake, now I am creating new pr so sry sir , I will provide
pr link within 2 hours sir .

**Comment by INam1995** [comment]
https://github.com/ContriHUB/CP-Grind/pull/13#issue-1944648512
sir this one is final PR.

**Pull request closed without merging**
